name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py migrate
          python manage.py test

      - name: Run code quality checks
        run: |
          flake8 .
          black --check .
          isort --check-only .

      - name: Run security checks
        run: |
          bandit -r .
          safety check

      - name: Run coverage
        run: |
          coverage run --source='.' manage.py test
          coverage report
          coverage html
